site_name: Utilities Docs
theme: 
  name: 'material'
  logo: 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/facebook/304/alien-monster_1f47e.png'
  favicon:
    'images/favicon.ico'
  features:
    - tabs
    - instant
  palette:
    scheme: preference
    primary: 'Blue Grey'
    accent: 'Cyan'
  font:
    text: 'Roboto'
    code: 'Fira Mono'
  
repo_name: 'Utlities Docs'
repo_url: 'https://github.com/eaglehunter2/utilities/'


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.keys
  - attr_list
  - pymdownx.betterem:
      smart_enable: all

google_analytics:
  - 'UA-126357432-1'
  - 'auto'

copyright: 'Copyright &copy; 2021'
